Add a GUI to showcase the abilities of the HVAC service
eclipse/kuksa.val.services pull request #41
Opened 2022-11-08 14:57 UTC by lukasmittag

GUI is implemented through the DearPyGUI (licenses need to be added before merging). It mocks a sensor and an application in the car or on a phone. Very lightweight and nothing too special.

2022-11-08 23:52 UTC, SebastianSchildt commented
Like the idea. Things I noticed: Should probably add all needed dependencies to Pipfile, missing was

```
grpcio
dearpygui
protobuf
```

dearpygui itself should not be a problem as new dependency (MIT),


When looking into the API migration we might also want to think about, whether we want to port/rewrite this demo in "Pure VSS" style, as this should be quite easy in this example. 

Found a little crash when putting the "Ratio to poll sensor" to 0

```
    if (count % sensor_ratio) == 0:
ZeroDivisionError: integer division or modulo by zero
``

2022-11-09 13:16 UTC, romainletendart commented on hvac_service/hvac_gui.py
> +    client = testclient.HVACTestClient("127.0.0.1:50052")
```suggestion
    hvac_addr = os.getenv("HVAC_ADDR", "127.0.0.1:50052")
    client = testclient.HVACTestClient(hvac_addr )
```
Let's make this configurable like in testclient.py.

2022-11-09 13:16 UTC, romainletendart commented on hvac_service/README.md
> +''' pip install dearpygui '''
I would move this to requirements.txt.

2022-11-11 14:57 UTC, SebastianSchildt requested changes
See comments

2022-11-11 14:57 UTC, SebastianSchildt commented on hvac_service/hvac_gui.py
> +import dearpygui.dearpygui as dpg
This needs a license header

2023-12-20 13:29 UTC, lukasmittag commented
Since there is the android companion app closing this

2023-12-20 13:29 UTC, closed without merging