extends documentation for vehicle mock service
eclipse/kuksa.val.services pull request #89
Opened 2023-08-02 12:48 UTC by eriksven

@doosuu, this PR extends the documentation for the vehicle mock service. Can you check whether the additions still reflect the state of the mock service? For instance, I am not sure whether the vehicle mock service actually uses the kuksa.val.v1 interface of the KUKSA.val databroker. The respective generated classes are part of the service but my IDE could not find any usage of this interface in the mock service.

2023-08-09 15:07 UTC, SebastianSchildt commented
I think we should rebase this on #88  , but that is still inr eview
With that PR Mock service is using the KUKSA client lib. That can be reflected iun the diagrams, and/or if still referring to the GRPC interface, it is solely kuksa.val.v1 then, with all the gnerated GRPC files (sdv or kuksa api) references gone

2023-08-10 05:02 UTC, doosuu requested changes
LGTM, but should be rebased on #88

2023-08-10 06:47 UTC, eriksven commented
@doosuu @lukasmittag  Thank you for the review. I rebased this PR on #88 and adapted the diagram accordingly so that the Vehicle Mock Service now uses the kuksa.val.v1 interface.

2023-08-21 13:20 UTC, doosuu commented
@eriksven  will have another look on this once #88 is merged and the changes in this PR only contain the relevant data.

2023-08-23 07:53 UTC, eriksven commented
@SebastianSchildt @doosuu I rebased this PR to main after #88 has been merged.

2023-08-23 14:14 UTC, lukasmittag approved these changes

2023-08-23 14:15 UTC, merged